### ISSUE TITLE
2021-08-24 daily log

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/javaDailyStudy#111]
## 오늘 학습한 내용
<strong><누구나 쉽게 이해할 수 있는 Git 입문></strong>
- 파일을 전 상태로 되돌리고 싶을 때?
  - 파일을 미리 복사해둔다!

<strong>문제점</strong>
1. 매번 복사하는 것은 매우 번거롭고 실수할 가능성이 높다
2. 규칙 없이 마음대로 이름을 정하면 어느 파일이 최신인지 파악하기 어렵다
3. 다수의 팀원과 공유한 파일을 동시에 편집하게 되면 내용이 지워질 가능성이 높다

<strong>해결책</strong>
- 위와 같은 문제들을 해결하기 위해 만들어진 것이 Git과 같은 버전 관리 시스템이다.
- Git이란 소스코드를 효과적으로 관리하기 위해 개발된 '분산형 버전 관리 시스템'이다.
원래는 Linux 소스코드를 관리할 목적으로 개발 되었다.
- Git에서는 소스코드가 변경된 이력을 쉽게 확인할 수 있고, 특정 시점에서 저장된 버전과 비교하거나 특정 시점으로 되돌아갈 수도 있다. 
- 내가 올리려는 파일이 누군가 편집한 내용과 충돌한다면, 서버에서 업로드 할 때 경고 메시지가 발생된다. 이를 통해 편집한 내용을 덮어써버리는 실수를 방지할 수 있다.

<strong>Git의 기본</strong>

- 이력을 관리하는 저장소
  - 저장소란 말그대로 파일이나 폴더를 저장해 두는 곳입니다. 그런데 Git 저장소가 제공하는 좋은 점 중 하나는 파일이 변경 이력 별로 구분되어 저장된다는 점입니다. 비슷한 파일이라도 실제 내용 일부 문구가 서로 다르면 다른 파일로 인식하기 때문에 파일을 변경 사항 별로 구분해 저장할 수 있습니다.

- 원격 저장소와 로컬 저장소
  - Git은 원격 저장소와 로컬 저장소 두 종류의 저장소를 제공합니다
    - 원격 저장소: 파일이 원격 저장소 전용 서버에서 관리되며 여러 사람이 함께 공유하기 위한 저장소입니다.
    - 로컬 저장소: 내 pc에 파일이 저장되는 개인 전용 저장소입니다.
  - 평소에는 내 pc의 로컬 저장소에서 작업하다가 작업한 내용을 공개하고 싶을 때에 원격 저장소에 업로드 합니다. 원격 저장소에서 다른 사람이 작업한 파일을 로컬 저장소로 가져올 수도 있습니다.

- 저장소 만들기
  -  내 컴퓨터에 로컬 저장소를 만드는 방법은 두 가지가 있습니다.
    1. 저장소를 새로 만든다
    2. 만들어져 있는 원격 저장소를 로컬 저장소로 복사해 온다.

- 변경을 기록하는 커밋
  - 파일 및 폴더의 추가/ 변경 사항을 저장소에 기록하려면 '커밋'이란 버튼을 눌러주어야 합니다.
  - 커밋 버튼을 누르면 이전 커밋 상태로부터 현재 상태까지의 변경 이력이 기록된 커밋(또는 리비전)이 만들어집니다.
  - 커밋은 시간순으로 저장되며 최근 커밋부터 거슬러 올라가면 과거 변경 이력과 내용을 알 수 있습니다.
  - 각 커밋에는 영문/숫자로 이루어진 40자리 고유 이름이 붙습니다. 저장소에선 이 40자리 이름을 보고 각 커밋을 구분하고 선택합니다.
  - 커밋은 이력을 남기는 중요한 작업이기에 커밋 메시지를 필수로 입력해야 합니다. 메시지가 없으면 커밋이 실행되지 않습니다.<br>
  <strong>ex</strong><br>
  1번째 줄: 커밋 내의 변경 내용을 요약<br>
  2번째 줄: 빈칸<br>
  3번째 줄: 변경 이유

- 작업 트리와 인덱스
  - Git에서는 우리가 흔히 말하는 폴더를 작업 트리라고 부릅니다 그리고 커밋을 실행하기 전의 저장소와 작업 트리 사이에 존재하는 공간을 인덱스라고 합니다.  
 
## 회고

**Comment by lette1394** [comment]
@Gyoung-min 
이제 어느정도는 이해되셨을거라고 생각합니다ㅎㅎ

스스로 추가 학습이 필요하다고 생각하시나요?
git 관련 문제가 있는 경우 무엇이 문제인지 정확히는 몰라도 혼자서 검색해서 해결할 수 있으실까요?
